<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2OU9P92" name="Test" tests="2" failures="2" timestamp="19 Jul 2020 03:42:22 GMT" time="0.041" errors="0">
  <testcase name="Tc_Login_001" time="0.025" classname="com.Automation.HoroLab.TestCases.Login">
    <failure type="java.lang.AssertionError" message="Fail due to exception null">
      <![CDATA[java.lang.AssertionError: Fail due to exception null
	at com.Automation.HoroLab.Modules.LoginPage.logIn(LoginPage.java:41)
	at com.Automation.HoroLab.TestCases.Login.Tc_Login_001(Login.java:12)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Tc_Login_001 -->
  <testcase name="Tc_Login_002" time="0.002" classname="com.Automation.HoroLab.TestCases.Login">
    <failure type="java.lang.AssertionError" message="Fail due to exception null">
      <![CDATA[java.lang.AssertionError: Fail due to exception null
	at com.Automation.HoroLab.Modules.LoginPage.logIn(LoginPage.java:41)
	at com.Automation.HoroLab.TestCases.Login.Tc_Login_002(Login.java:19)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Tc_Login_002 -->
</testsuite> <!-- Test -->
